services:
  postgres:
    image: ankane/pgvector:latest   # This image includes the vector extension
    container_name: postgres_db
    environment:
      POSTGRES_USER: nlp_user
      POSTGRES_PASSWORD: nlp_password
      POSTGRES_DB: nlp_db
    ports:
      - "6012:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: